# More information on gocd-flavor YAML can be found here:
# - https://github.com/tomzo/gocd-yaml-config-plugin#pipeline
# - https://www.notion.so/sentry/GoCD-New-Service-Quickstart-6d8db7a6964049b3b0e78b8a4b52e25d
format_version: 10
pipelines:
  deploy-session-replay-analyzer:
    environment_variables:
      GCP_PROJECT: internal-sentry
      GKE_CLUSTER: zdpwkxst
      GKE_REGION: us-central1
      GKE_CLUSTER_ZONE: b
      GKE_BASTION_ZONE: b
      # Required for checkruns.
      GITHUB_TOKEN: "{{SECRET:[devinfra-github][token]}}"
    group: session-replay-analyzer
    lock_behavior: unlockWhenFinished
    materials:
      session-replay-analyzer_repo:
        git: git@github.com:getsentry/session-replay-analyzer.git
        shallow_clone: true
        branch: main
        destination: session-replay-analyzer
    stages:
      - checks:
          jobs:
            checks:
              timeout: 1200
              elastic_profile_id: session-replay-analyzer
              tasks:
                - script: |
                    /devinfra/scripts/checks/githubactions/checkruns.py \
                    getsentry/session-replay-analyzer \
                    ${GO_REVISION_SESSION_REPLAY_ANALYZER_REPO} \
                    "build-image (amd64)"
                - script: |
                    /devinfra/scripts/checks/googlecloud/checkcloudbuild.py \
                    ${GO_REVISION_session-replay-analyzer_REPO} \
                    sentryio \
                    "us.gcr.io/sentryio/session-replay-analyzer"
      - deploy-canary:
          jobs:
            deploy:
              timeout: 600
              elastic_profile_id: session-replay-analyzer
              tasks:
                - script: |
                    /devinfra/scripts/k8s/k8stunnel \
                    && /devinfra/scripts/k8s/k8s-deploy.py \
                    --context="gke_${GCP_PROJECT}_${GKE_REGION}-${GKE_CLUSTER_ZONE}_${GKE_CLUSTER}" \
                    --label-selector="service=session-replay-analyzer,env=canary" \
                    --image="us.gcr.io/sentryio/session-replay-analyzer:${GO_REVISION_session-replay-analyzer_REPO}" \
                    --container-name="session-replay-analyzer"
                - script: |
                    /devinfra/scripts/canary/canarychecks.py \
                    --wait-minutes=5
      - deploy-primary:
          jobs:
            deploy:
              timeout: 600
              elastic_profile_id: session-replay-analyzer
              tasks:
                - script: |
                    /devinfra/scripts/k8s/k8stunnel \
                    && /devinfra/scripts/k8s/k8s-deploy.py \
                    --context="gke_${GCP_PROJECT}_${GKE_REGION}-${GKE_CLUSTER_ZONE}_${GKE_CLUSTER}" \
                    --label-selector="service=session-replay-analyzer" \
                    --image="us.gcr.io/sentryio/session-replay-analyzer:${GO_REVISION_session-replay-analyzer_REPO}" \
                    --container-name="session-replay-analyzer"
