name: build
on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: npm install --prefix player
      - run: npm run build --prefix player
      - run: npm install --prefix server
      - run: npm run build --prefix server
      - run: mv player/dist/index.html server/dist/index.html
      - run: mv player/dist/player.js server/dist/player.js
      - run: npm run test --prefix server
      - if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: snapshot diffs
          path: tests/__image_snapshots__
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.sha }}
          path: |
            ${{ github.workspace }}/*.tgz
