name: build
on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: rm -rf player
      - run: npm install
      - run: npm run build
      - run: cp -r mock dist/mock
      - run: npm run test
      - run: npm run test-playwright
      - if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: snapshot diffs
          path: tests/__image_snapshots__
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.sha }}
          path: |
            ${{ github.workspace }}/*.tgz
